'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Create_form

    '''<summary>
    '''create_form control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents create_form As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''txt_deptcode_create control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_deptcode_create As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_deptname_create control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_deptname_create As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_remarks_create control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_remarks_create As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddl_status_create control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_status_create As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''button_create_department control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents button_create_department As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txt_empcode_create control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_empcode_create As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_empdeptcode_create control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_empdeptcode_create As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_firstname_create control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_firstname_create As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_lastname_create control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_lastname_create As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''button_create_employee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents button_create_employee As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''grid_deptcodename control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grid_deptcodename As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grid_all_deptemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grid_all_deptemp As Global.System.Web.UI.WebControls.GridView
End Class
