'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class dept_form

    '''<summary>
    '''dept_emp_form control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dept_emp_form As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''txt_deptcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_deptcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_deptname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_deptname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddl_deptstatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_deptstatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''button_search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents button_search As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''button_reset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents button_reset As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txt_selected_deptcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_selected_deptcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''button_delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents button_delete As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''button_clear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents button_clear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''grid_department control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grid_department As Global.System.Web.UI.WebControls.GridView
End Class
