'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Edit_DeptEmp

    '''<summary>
    '''edit_form control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents edit_form As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''txt_deptcode_update control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_deptcode_update As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_deptname_update control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_deptname_update As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_remarks_update control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_remarks_update As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddl_status_update control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_status_update As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''button_update_department control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents button_update_department As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txt_empcode_update control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_empcode_update As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_firstname_update control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_firstname_update As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_lastname_update control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_lastname_update As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_deptcode_update2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_deptcode_update2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''button_update_employee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents button_update_employee As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''grid_dept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grid_dept As Global.System.Web.UI.WebControls.GridView
End Class
